# Generated by Django 3.1.3 on 2020-11-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_stock_shares_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency_type',
            field=models.CharField(default='stock', max_length=50),
        ),
    ]
