# Generated by Django 3.1.3 on 2020-11-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20201126_1244'),
        ('quotes', '0004_auto_20201126_2206'),
    ]

    operations = [
    ]
